### ISSUE TITLE
Request to add Any option in Yaml config for use of both OS

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#184]
# Announce remote device trackers. The server doesn't check their availability.
remoteHostList:
  **- useProxy: true   # optional, default: false
    type: android    # required, "android" | "ios"
    secure: true     # required, false for HTTP, true for HTTPS
    hostname: second-mobile-stand.example.com
    port: 8443
  - useProxy: true
    type: ios
    secure: true
    hostname: second-mobile-stand.example.com
    port: 8443**

instead of repeating host info twice, why not use it as --

- useProxy: true   # optional, default: false
    type: **_Any_**    # required, "android" | "ios"
    secure: true     # required, false for HTTP, true for HTTPS
    hostname: second-mobile-stand.example.com
    port: 8443

**Comment by krishtoautomate** [comment]
type: Any # required, "android" | "ios" | "**Any**"

**Comment by drauggres** [comment]
I would prefer to change it in this way:

```typescript

type OperatingSystem = 'android' | 'ios';

interface HostItem {
    type: OperatingSystem | OperatingSystem[];
    secure: boolean;
    hostname: string;
    port: number;
    useProxy?: boolean;
}
```

e.g.

```yaml
remoteHostList:
- useProxy: true
  type:
  - ios
  - android
  secure: true
  hostname: third-mobile-stand.example.com
  port: 8443
```
