### ISSUE TITLE
Can I found new devices from another machine? 

### ISSUE THREAD

**Issue by ZHENGYUN01** [NetrisTV/ws-scrcpy#204]
I deploy ws-scrcpy onto a linux machine, and then i visit the ws-scrcpy from a win10 machine which my android phone connected to the very win10 machine, but from the web browser, i could not found my device.

ws-scrcpy: deployed on linux machine A
 
a android device connected to win10(machine B) 

web browser in a win10 (machine B): visit ws-scrcpy, could not found my andori device.

**Comment by ZHENGYUN01** [comment]
I try to edit config file and then specify a env variable WS_SCRCPY_CONFIG=./, but works failed.
```sh
export WS_SCRCPY_CONFIG=/home/work/ws-scrcpy/config.example.yaml
```
```
# Run configuration example. See full config file spec in src/types/Configuration.d.ts

# Device trackers (default: true)
runGoogTracker: true
runApplTracker: false;

# HTTP[s] servers configuration
server:
  - secure: false
    port: 8000
    redirectToSecure:
      port: 8443
      host: {my linux ip}
  - secure: false
    port: 8000
    options:
      certPath: /Users/example/ssl/STAR_example_com.crt
      keyPath: /Users/example/ssl/STAR_example_com.key

# Announce remote device trackers. The server doesn't check their availability.
remoteHostList:
  - useProxy: true   # optional, default: false
    type: android    # required, "android" | "ios" | ["android", "ios"]
    secure: false    # required, false for HTTP, true for HTTPS
    hostname: {my linux ip}
    port: 8000
  - useProxy: true
    type: ios
    secure: false
    hostname: {my linux ip}
    port: 8000
  - useProxy: true
    type:           # short variant
      - ios
      - android
    secure: false
    hostname: {my linux ip}
    port: 8000
```


could you please to give me a example for a configuration file?
